### ISSUE TITLE
Evaluate Open Cyber Security Conference Sponsorship

### ISSUE THREAD

**Issue by oliverrochford** [tenzir/events#2]
```[tasklist]
### Tasks
- [ ] Plan out event sponsorship
- [ ] Speak to OCSF
- [ ] Update Estimate
```

**Comment by oliverrochford** [comment]
[OCSC2024-Sponsorship-V4.pdf](https://github.com/tenzir/events/files/12212903/OCSC2024-Sponsorship-V4.pdf)

https://docs.google.com/document/d/1X32e8e3l1AkOAboO5w5DQbR2ublJi6_1PXsm_N7VHMU/edit

**Comment by oliverrochford** [comment]
Spoke to Silvio Oertli, Chair of TF-CSIRT

- Monday and Friday are trainings
- Monday evening is icebreaker
- Tuesday - Thursday are for presentations
- Vendor booths will be in the foyer and we can interact with the attendees during talk breaks
- Tuesday evening will also be an occasion to interact
- We could also offer a training

Suggested we travel in on Monday for the icebreaker, and stay till Thursday

**Comment by mavam** [comment]
> Suggested we travel in on Monday for the icebreaker, and stay till Thursday

So no sponsoring, right?

**Comment by mavam** [comment]
Decided with Johan as "go only"
